name: Update latest social posts

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fetch latest TikTok (RSSHub → rss2json)
        shell: bash
        run: |
          set -uo pipefail
          mkdir -p data
          USER_TT="andrewtvi"

          API="https://api.rss2json.com/v1/api.json?rss_url=$(python3 - <<'PY'
import urllib.parse
print(urllib.parse.quote(f'https://rsshub.app/tiktok/user/{\"andrewtvi\"}', safe=''))
PY
)"
          JSON="$(curl -fsSL "$API" || echo '{}')"
          TTK="$(python3 - <<'PY'
import json,sys
j=json.loads(sys.stdin.read() or '{}')
print((j.get('items') or [{}])[0].get('link',''))
PY
<<< "$JSON")"

          # deja Twitter vacío (lo maneja Cloudflare Worker)
          echo "{\"tiktok\":\"$TTK\",\"tweet\":\"\"}" > data/latest.json

      - name: Commit & push
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update data/latest.json (tiktok)"
          file_pattern: data/latest.json
