name: Update latest social posts

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install tools
        shell: bash
        run: |
          set -uo pipefail
          sudo apt-get update -y >/dev/null
          sudo apt-get install -y jq curl >/dev/null

      - name: Fetch latest TikTok (via r.jina.ai)
        shell: bash
        run: |
          set -uo pipefail
          mkdir -p data

          USER_TT="andrewtvi"

          # Scrapea la página de TikTok con r.jina.ai
          RAW="$(curl -fsSL "https://r.jina.ai/http://www.tiktok.com/@${USER_TT}" || true)"

          # Busca el primer video válido en el HTML
          TTK="$(printf '%s' "$RAW" | grep -oE 'https://www.tiktok.com/@'${USER_TT}'/video/[0-9]+' | head -n 1 || true)"

          # Si no encuentra nada, deja vacío
          TTK="${TTK:-""}"

          # Guardamos con tweet vacío (lo llenará tu Worker)
          printf '%s\n' "{\"tiktok\":\"$TTK\",\"tweet\":\"\"}" > data/latest.json

      - name: Commit & push
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update data/latest.json (tiktok)"
          file_pattern: data/latest.json
