name: Update latest social posts

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install tools
        shell: bash
        run: |
          set -uo pipefail
          sudo apt-get update -y >/dev/null
          sudo apt-get install -y jq >/dev/null

      - name: Fetch latest TikTok (RSSHub → rss2json) con tolerancia
        shell: bash
        run: |
          set -uo pipefail
          mkdir -p data

          USER_TT="andrewtvi"

          # URL-encode usando jq (sin Python)
          RSS_URL_ENC=$(printf '%s' "https://rsshub.app/tiktok/user/${USER_TT}" | jq -sRr @uri)
          API="https://api.rss2json.com/v1/api.json?rss_url=${RSS_URL_ENC}"

          # Descarga con reintentos; si falla, dejamos JSON vacío
          JSON="$(curl -fsSL --retry 2 --retry-delay 2 "$API" || echo '{}')"

          # Extrae link del primer item (si existe)
          TTK="$(printf '%s' "$JSON" | jq -r '.items[0].link // ""')"

          # Guardamos dejando tweet vacío (lo maneja tu Worker)
          printf '%s\n' "{\"tiktok\":\"$TTK\",\"tweet\":\"\"}" > data/latest.json

      - name: Commit & push
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update data/latest.json (tiktok)"
          file_pattern: data/latest.json
