name: Update latest social posts

on:
  schedule:
    - cron: '*/30 * * * *'       # cada 30 minutos
  workflow_dispatch: {}           # ejecución manual

permissions:
  contents: write                 # necesario para commit

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fetch latest TikTok & Tweet via r.jina.ai (robusto)
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p data

          # 1) Último TikTok: usamos el fetcher de sólo lectura r.jina.ai
          #    y extraemos el primer enlace /video/ del usuario.
          TIKTOK_PAGE_URL="https://r.jina.ai/http://www.tiktok.com/@andrewtvi"
          TIKTOK=$(curl -fsSL "$TIKTOK_PAGE_URL" \
            | grep -oE "https://www\.tiktok\.com/@andrewtvi/video/[0-9]+" \
            | head -n1 || true)

          # 2) Último Tweet: miramos Nitter "renderizado" y convertimos a twitter.com
          NITTER_PAGE_URL="https://r.jina.ai/http://nitter.net/iandres_soto"
          TWEET_NITTER=$(curl -fsSL "$NITTER_PAGE_URL" \
            | grep -oE "https://nitter\.net/iandres_soto/status/[0-9]+" \
            | head -n1 || true)
          TWEET="${TWEET_NITTER/https:\/\/nitter.net\//https:\/\/twitter.com/}"

          echo "TIKTOK: $TIKTOK"
          echo "TWEET : $TWEET"

          # Generar JSON (aunque vengan vacíos, para que siempre haya archivo)
          TIKTOK_SAFE=${TIKTOK//\"/\\\"}
          TWEET_SAFE=${TWEET//\"/\\\"}
          printf '{ "tiktok": "%s", "tweet": "%s" }\n' "$TIKTOK_SAFE" "$TWEET_SAFE" > data/latest.json

          echo "latest.json:"
          cat data/latest.json

      - name: Commit & push if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update latest.json"
          file_pattern: data/latest.json
