name: Update latest social posts

on:
  schedule:
    - cron: '*/30 * * * *'   # cada 30 minutos
  workflow_dispatch: {}       # ejecutarlo manualmente

permissions:
  contents: write             # necesario para hacer commit al repo

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fetch latest TikTok & Tweet (rss2json + jq)
        shell: bash
        run: |
          set -euxo pipefail
          mkdir -p data

          sudo apt-get update -y
          sudo apt-get install -y jq

          # Pedimos JSON ya parseado desde rss2json (evitamos XML / xmllint)
          TIKTOK_JSON="$(curl -fsSL 'https://api.rss2json.com/v1/api.json?rss_url=https%3A%2F%2Frsshub.app%2Ftiktok%2Fuser%2Fandrewtvi' || echo '{}')"
          TWEET_JSON="$(curl -fsSL 'https://api.rss2json.com/v1/api.json?rss_url=https%3A%2F%2Fnitter.net%2Fiandres_soto%2Frss' || echo '{}')"

          TIKTOK="$(echo "$TIKTOK_JSON" | jq -r '.items[0].link // empty')"
          TWEET_NITTER="$(echo "$TWEET_JSON" | jq -r '.items[0].link // empty')"
          TWEET="${TWEET_NITTER/https:\/\/nitter.net\//https:\/\/twitter.com/}"

          # Escapar comillas simples para JSON
          TIKTOK_SAFE="${TIKTOK//\"/\\\"}"
          TWEET_SAFE="${TWEET//\"/\\\"}"

          printf '{ "tiktok": "%s", "tweet": "%s" }\n' "$TIKTOK_SAFE" "$TWEET_SAFE" > data/latest.json
          echo "latest.json generado:"
          cat data/latest.json

      - name: Commit & push if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update latest.json"
          file_pattern: data/latest.json
