name: Update latest social posts

on:
  schedule:
    - cron: '*/30 * * * *'   # corre cada 30 minutos
  workflow_dispatch: {}       # permite ejecutarlo manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fetch latest TikTok & Tweet
        run: |
          mkdir -p data
          # RSS públicos
          curl -s "https://rsshub.app/tiktok/user/andrewtvi" > /tmp/tt.xml || true
          curl -s "https://nitter.net/iandres_soto/rss" > /tmp/tw.xml || true

          sudo apt-get update -y
          sudo apt-get install -y libxml2-utils

          # Primer <item><link> de cada feed
          TIKTOK=$(xmllint --xpath 'string((//item/link)[1])' /tmp/tt.xml 2>/dev/null || echo "")
          TWEET_NITTER=$(xmllint --xpath 'string((//item/link)[1])' /tmp/tw.xml 2>/dev/null || echo "")
          TWEET=${TWEET_NITTER/https:\/\/nitter.net\//https:\/\/twitter.com/}

          # Escapar comillas por seguridad simple
          TIKTOK_SAFE=$(printf '%s' "$TIKTOK" | sed 's/"/\\"/g')
          TWEET_SAFE=$(printf '%s' "$TWEET" | sed 's/"/\\"/g')

          printf '{ "tiktok": "%s", "tweet": "%s" }\n' "$TIKTOK_SAFE" "$TWEET_SAFE" > data/latest.json
          echo "latest.json:"
          cat data/latest.json

      - name: Commit & push if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update latest.json"
          file_pattern: data/latest.json
